CREATE TABLE DOCTOR
(
    NAME VARCHAR2(20) ,
    SPECIALIZATION CHAR(2),
    FEE NUMBER,
    CONSTRAINT D_NAME_SPEC PRIMARY KEY ( NAME, SPECIALIZATION )
);

CREATE TABLE PATIENT
(
    PATIENT_NO  CHAR(5) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(10),
);

CREATE TABLE APPOINTMENT
(
    PATIENT_NO  CHAR(5),
    NAME VARCHAR2(20),
    SPECIALIZATION VARCHAR2(2),
    CONSTRAINT A_NAME_SPEC PRIMARY KEY ( PATIENT_NO, NAME,SPECIALIZATION )
);

ALTER TABLE APPOINTMENT ADD APPOINTMENT_DATE DATE;

ALTER TABLE APPOINTMENT RENAME PATIENT_NO TO P_NO ;

ALTER TABLE APPOINTMENT RENAME NAME TO D_NAME ;

ALTER TABLE APPOINTMENT RENAME TO  APPOINTMENT_INFO ;

CONSTRAINT FK_APPOINTMENT_DOCTOR FOREIGN KEY (D_NAME,SPECIALIZATION,P_NO);

CONSTRAINT FK_APPOINTMENT_PATIENT FOREIGN KEY(D_NAME,SPECIALIZATION,P_NO)
REFERENCES APPOINTMENT(D_NAME,SPECIALIZATION,P_NO) ON DELETE DEFAULT;

INSERT INTO DOCTOR ('MR. X','CS',2000);
INSERT INTO DOCTOR ('MR. Y',' GS',1500);
INSERT INTO DOCTOR ('MR.Z','ER',1000);
INSERT INTO PATIENT('P-101','A','DHK');
INSERT INTO PATIENT('P-102','B','DHV');
INSERT INTO PATIENT('P-103','C','DHL');
INSERT INTO APPOINTMENT_INFO('P-101','MR. X','CS');
INSERT INTO APPOINTMENT_INFO('P-102','MR. Y','GS');
INSERT INTO APPOINTMENT_INFO('P-103','MR. Z','ER');

SELECT NAME FROM DOCTOR WHERE (FEE>1500);

SELECT NAME FROM  PATIENT WHERE ADDRESS = 'KHL' ;

SELECT PATIENT.PATIENT_NO,PATIENT.NAME,PATIENT.ADDRESS,APPOINTMENT_INFO.PATIENT_NO,APPOINTMENT_INFO.NAME,APPOINTMENT_INFO.SPECIALIZATION  FROM APPOINTMENT_INFO,PATIENT;

SELECT * FROM APPOINTMENT_INFO NATURAL JOIN PATIENT;

SELECT NAME,ADDRESS  FROM  PATIENT NATURAL JOIN APPOINTMENT WHERE (APPOINTMENT_DATE = '28-AUG-23');

SELECT FEE,SPECIALIZATION,NAME
FROM PATIENT NATURAL JOIN DOCTOR
WHERE (ADDRESS = 'DHK');

SELECT PATIENT_NO,NAME,ADDRESS FROM  DOCTOR NATURAL JOIN PATIENT
WHERE (SPECIALIZATION='GS'OR FEE <1500);

UPDATE NAME,ADDRESS
SET NAME = 'K', ADDRESS = 'RAJ'
WHERE NAME = 'A'AND ADDRESS = 'DHK';

UPDATE NAME SET NAME = 'Ms. Y' WHERE NAME = 'MR. Y';

DELETE FROM PATIENT WHERE PATIENT_NO = 'P-101';

DELETE FROM APPOINTMENT,PATIENT,DOCTOR;
