CREATE TABLE STUDENT (
ID NUMBER NOT NULL ;
NAME VARCHAR2(50) NOT NULL ;
DEPT_NAME VARCHAR2(50);
TOT_CRED NUMBER(180,1) ;
PRIMARY KEY(ID);
);




INSERT INTO STUDENT VALUES (00128,"Zhang","Comp. Sci.",102);
INSERT INTO STUDENT VALUES (12345,"Shankar","Comp. Sci.",32);
INSERT INTO STUDENT VALUES (19991,"Brandt","History",80);
INSERT INTO STUDENT VALUES (23121,"Chavez","Finance",110);
INSERT INTO STUDENT VALUES (44553,"Peltier","Physics",56);
INSERT INTO STUDENT VALUES (45678,"Levy","Physics",46);
INSERT INTO STUDENT VALUES (54321,"Williams","Comp. Sci.",5);
INSERT INTO STUDENT VALUES (55739,"Sanchez","Music",38);
INSERT INTO STUDENT VALUES (70557," Snow","Physics",0);
INSERT INTO STUDENT VALUES (76543,"Brown","Comp. Sci.",58);
INSERT INTO STUDENT VALUES (76653,"Aoi","Elec. Eng.",60);
INSERT INTO STUDENT VALUES (98765,"Bourikas","Elec. Eng.",9);
INSERT INTO STUDENT VALUES (98988,"Tanaka","Biology",120);

SELECT * FROM STUDENT ;

SELECT ID,NAME FROM STUDENT;

SELECT NAME,DEPT_NAME FORM STUDENT WHERE TOT_CRED < 100 ;

SELECT NAME,DEPT_NAME FORM STUDENT WHERE TOT_CRED <= 120 AND TOT_CRED >= 80;

SELECT ID,NAME FROM STUDENT WHERE DEPT_NAME = 'Comp. Sci.';

SELECT NAME,TOT_CRED FROM STUDENT WHERE DEPT_NAME = 'Physics';

SELECT ID,NAME FROM STUDENT WHERE DEPT_NAME = 'Physics' OR TOT_CRED > 10 ;

SELECT DEPT_NAME FROM STUDENT;

DROP TABLE STUDENT;

