SET SERVEROUTPUT ON ;

/*FIRST TASK : PRINTING NAME AS CONST VARIBLES */
DECLARE
USERNAME VARCHAR(20);
BEGIN
USERNAME := 'AHMED M. S. ALBREEM';
DBMS_OUTPUT.PUT_LINE(USERNAME);
END;
/

/*SECOND TASK : */
DECLARE
STUDENT_ID VARCHAR2(20);
BEGIN
STUDENT_ID := '210041258';
DBMS_OUTPUT.PUT_LINE(LENGTH(STUDENT_ID));
END;
/

/*THIRD TASK : */
DECLARE
VAR1 NUMBER:= 1;VAR2 NUMBER := 1;
VAR3 NUMBER := 1;
BEGIN
VAR1 := 2;
VAR2 := 3;
VAR3 := VAR1 * VAR2;
DBMS_OUTPUT.PUT_LINE('THE NUMBER VAR1 AS '|| VAR1 || ' , THE NUMBER VAR2 AS ' || VAR2 || ' , THE NUMBER VAR3 AS RESULT OF THE PRODUCT OPERATION OF THE VAR1 AND VAR2 AS : ' || VAR3);
END;
/

/*FOURTH TASK AS CHAR : */
DECLARE
MYSYS_TIME VARCHAR(30);
BEGIN
MYSYS_TIME :=  TO_CHAR(SYSDATE,'MM/DD/YYYY HH:MI:SS AM');
DBMS_OUTPUT.PUT_LINE('THE TODAY TIME : ' || MYSYS_TIME );
END;
/

/*FOURTH TASK AS DATE : */
DECLARE
MYSYS_TIME DATE;
BEGIN
/*IN SPACIAL CASES WE CAN USE IT WITH MULTI-OPERATION */
MYSYS_TIME :=  SYSDATE;
DBMS_OUTPUT.PUT_LINE('THE TODAY TIME : ' || TO_CHAR(MYSYS_TIME,'MM/DD/YYYY HH:MI:SS AM') );
END;
/


/* FIFTH TASK : */

DECLARE
I NUMBER(2);
TYPE NumberArray IS TABLE OF NUMBER(10,3) INDEX BY BINARY_INTEGER;
VAR NumberArray;
BEGIN
VAR(2):=3.005;
VAR(1):=3.000;
FOR I IN 1 .. 2 LOOP
IF (VAR(I) MOD 1 = 0) THEN
DBMS_OUTPUT.PUT_LINE('THE NUMBER (' || VAR(I)||') HAVENT''T FRACTION SIDE ' );
ELSE
DBMS_OUTPUT.PUT_LINE('THE NUMBER(' || VAR(I)||') HAVE FRACTION SIDE');
END IF;
END LOOP;
END;

/*SIXTH TASK PART ONE : (THE CREATION OF THE FUNCTION ON THE START)*/
CREATE OR REPLACE FUNCTION CHECK_NUMS_IS_MOD(VAR1 NUMBER)
RETURN BOOLEAN IS
I NUMBER;
BEGIN
IF VAR1<=1 THEN
RETURN FALSE;
END IF;
FOR I IN 2..TRUNC(SQRT(VAR1)) LOOP
IF  MOD(VAR1,I) = 0 THEN
RETURN TRUE;
END IF;
END LOOP;
RETURN FALSE;
END CHECK_NUMS_IS_MOD;



/*SIXTH TASK PART TWO : ( THE REQUEST FOR THE FUNCTION FROM THE NORMAL REQUEST)*/
DECLARE
I NUMBER;
RESULT BOOLEAN ;
BEGIN
I := 7.000;
RESULT := CHECK_NUMS_IS_MOD(I);
IF RESULT THEN
DBMS_OUTPUT.PUT_LINE('THE NUMBER ('|| I ||') IS  COMPOSITE NUMBER ');
ELSE
DBMS_OUTPUT.PUT_LINE('THE NUMBER (' || I || ') IS NOT COMPOSITE NUMBER ');
END IF;
END;

/*  seventh task part one : (createion of the function )*/
CREATE OR REPLACE PROCEDURE TOP_RATED(N IN NUMBER) AS
BEGIN
  FOR ROW IN (
    SELECT MOV.MOV_ID, MOV.MOV_TITLE, MOV.MOV_YEAR, MOV.MOV_TIME, MOV.MOV_LANGUAGE, MOV.MOV_RELEASEDATE, MOV.MOV_COUNTRY
    FROM MOV_TITLE MOV
    JOIN RATING ON RATING.MOV_ID = MOV.MOV_ID
    WHERE ROWNUM <= N
    ORDER BY RATING.REV_STARS DESC
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('Movie ID: ' || ROW.MOV_ID);
    DBMS_OUTPUT.PUT_LINE('Movie Title: ' || ROW.MOV_TITLE);
    DBMS_OUTPUT.PUT_LINE('Movie YEAR: ' || ROW.MOV_YEAR);
    DBMS_OUTPUT.PUT_LINE('Movie TIME: ' || ROW.MOV_TIME);
    DBMS_OUTPUT.PUT_LINE('Movie LANGUAGE: ' || ROW.MOV_LANGUAGE);
    DBMS_OUTPUT.PUT_LINE('Movie RELEASEDATE: ' || TO_CHAR(ROW.MOV_RELEASEDATE, 'YYYY-MM-DD'));
    DBMS_OUTPUT.PUT_LINE('Movie COUNTRY: ' || ROW.MOV_COUNTRY);
    DBMS_OUTPUT.PUT_LINE('-------------------------------------');
  END LOOP;
END;

BEGIN TOP_RATED(3); END;


/* EIGTH TASK : (CREATION OF THE FUNCTION)*/

CREATE OR REPLACE FUNCTION MOVIE_STATE(_MOVIE_TITLE_ IN VARCHAR) RETURN VARCHAR IS
  _STATE VARCHAR;
  _SUM NUMBER;
BEGIN
  SELECT SUM(ACT_ID)
  INTO _SUM
  FROM MOVIE
  JOIN CASTS ON CASTS.MOV_ID = MOVIE.MOV_ID
  WHERE MOVIE.MOV_TITLE = _MOVIE_TITLE_;

  IF _SUM > 1 THEN
    _STATE := 'Ensemble';
  ELSE
    _STATE := 'SOLO';
  END IF;

  DBMS_OUTPUT.PUT_LINE('THE MOVIE TITLE : ' || _MOVIE_TITLE_);
  DBMS_OUTPUT.PUT_LINE('THE SUM OF THE WORKER : ' || _SUM);
  DBMS_OUTPUT.PUT_LINE('THE STATE OF THE MOVIE : ' || _STATE);

  RETURN _STATE;
END;
/

BEGIN
MOVIE_STATE('Vertigo');
END;
/

/* NINTH TASK : (CRAETION OF THE FUNCTION) */
CREATE OR REPLACE PROCEDURE FindOscarNominees AS
BEGIN
    FOR director_data IN (
        SELECT d.DIR_FIRSTNAME, d.DIR_LASTNAME
        FROM DIRECTOR d
        WHERE EXISTS (
            SELECT 1
            FROM MOVIE m
            JOIN RATING r ON m.MOV_ID = r.MOV_ID
            WHERE m.MOV_ID IN (
                SELECT MOV_ID
                FROM DIRECTION
                WHERE DIR_ID = d.DIR_ID
            )
            AND AVG(r.REV_STARS) >= 7
            AND (SELECT COUNT(*) FROM RATING WHERE MOV_ID = m.MOV_ID) > 10
        )
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Possible Oscar Nominee: ' || director_data.DIR_FIRSTNAME || ' ' || director_data.DIR_LASTNAME);
    END LOOP;
END;

/*THE TENTH TASK : (CREATION OF THE FUNCTION )*/

CREATE OR REPLACE FUNCTION GetMovieCategory(p_movie_title IN VARCHAR2) RETURN VARCHAR2 IS
    v_category VARCHAR2;
    v_year NUMBER;
    v_avg_rating NUMBER;
BEGIN
    v_category := 'Garbage';

    FOR movie_data IN (
        SELECT m.MOV_YEAR, AVG(r.REV_STARS) AS AVG_RATING
        FROM MOVIE m
        LEFT JOIN RATING r ON m.MOV_ID = r.MOV_ID
        WHERE m.MOV_TITLE = p_movie_title
        GROUP BY m.MOV_YEAR
    ) LOOP
        v_year := movie_data.MOV_YEAR;
        v_avg_rating := movie_data.AVG_RATING;

        IF v_year BETWEEN 1950 AND 1959 AND v_avg_rating > 6.5 THEN
            v_category := 'Fantastic Fifties';
        ELSIF v_year BETWEEN 1960 AND 1969 AND v_avg_rating > 6.7 THEN
            v_category := 'Sweet Sixties';
        ELSIF v_year BETWEEN 1970 AND 1979 AND v_avg_rating > 6.9 THEN
            v_category := 'Super Seventies';
        ELSIF v_year BETWEEN 1980 AND 1989 AND v_avg_rating > 7.1 THEN
            v_category := 'Ecstatic Eighties';
        ELSIF v_year BETWEEN 1990 AND 1999 AND v_avg_rating > 7.3 THEN
            v_category := 'Neat Nineties';
        END IF;
    END LOOP;

    RETURN v_category;
END;
/


