CREATE TABLE DOCTOR(
NAME VARCHAR2(20),
SPECIALIZATION CHAR(2),
FEE NUMBER,
PRIMARY KEY (NAME,SPECIALIZATION)
);

CREATE TABLE PATIENT(
PATIENT_NO CHAR(5) PRIMARY KEY ,
NAME VARCHAR(20) NOT NULL,
ADDERSS VARCHAR2(10)
);

CREATE TABLE APPOINTMENT(
PATIENT_NO CHAR(5),
NAME VARCHAR(20),
SPECIALIZATION CHAR(2),
CONSTRAINT PK_APP_PA PRIMARY KEY (PATIENT_NO,NAME,SPECIALIZATION)
);

ALTER TABLE APPOINTMENT ADD APPOINTMENT_DATE DATE;
ALTER TABLE APPOINTMENT DROP CONSTRAINT PK_APP_PA;
ALTER TABLE APPOINTMENT ADD CONSTRAINT NEW_PK_APP_PA PRIMARY KEY (PATIENT_NO,NAME,SPECIALIZATION,APPOINTMENT_DATE);
ALTER TABLE APPOINTMENT RENAME COLUMN PATIENT_NO TO P_NO;
ALTER TABLE APPOINTMENT RENAME COLUMN NAME TO D_NAME;
ALTER TABLE APPOINTMENT RENAME TO APPOINTMENT_INFO ;
/*(*~*)*/
ALTER TABLE APPOINTMENT_INFO ADD CONSTRAINT FK_APPOINTMENT_DOCTOR FOREIGN KEY(D_NAME,SPECIALIZATION)
REFERENCES DOCTOR(NAME,SPECIALIZATION) ON DELETE CASCADE;
ALTER TABLE APPOINTMENT_INFO ADD CONSTRAINT FK_APPOINTMENT_PATIENT FOREIGN KEY(P_NO)
REFERENCES PATIENT(PATIENT_NO) ON DELETE CASCADE;
/*(*-*)*/

INSERT INTO DOCTOR(NAME,SPECIALIZATION,FEE) VALUES('MR. X','CS',2000);
INSERT INTO DOCTOR(NAME,SPECIALIZATION,FEE) VALUES('MR. Y','GS',1500);
INSERT INTO DOCTOR(NAME,SPECIALIZATION,FEE) VALUES('MR. Z','SS',1000);

INSERT INTO PATIENT(PATIENT_NO,NAME,ADDERSS) VALUES('P-101','A','DHK');
INSERT INTO PATIENT(PATIENT_NO,NAME,ADDERSS) VALUES('P-102','B','KHL');
INSERT INTO PATIENT(PATIENT_NO,NAME,ADDERSS) VALUES('P-103','C','SQD');

INSERT INTO APPOINTMENT_INFO(PATIENT_NO,NAME,SPECIALIZATION,APPOINTMENT_DATE) VALUES('P-101','MR. X','CS','01-SEP-23');
INSERT INTO APPOINTMENT_INFO(PATIENT_NO,NAME,SPECIALIZATION,APPOINTMENT_DATE) VALUES('P-102','MR. Y','GS','02-SEP-23');
INSERT INTO APPOINTMENT_INFO(PATIENT_NO,NAME,SPECIALIZATION,APPOINTMENT_DATE) VALUES('P-103','MR. Z','SS','03-SEP-24');

SELECT NAME FROM DOCTOR WHERE (FEE<=1500);
SELECT NAME FROM PATIENT WHERE (ADDERSS = 'KHL');
SELECT * FROM PATIENT,APPOINTMENT_INFO WHERE (PATIENT.PATIENT_NO=APPOINTMENT_INFO.PATIENT_NO);
SELECT * FROM PATIENT NATURAL JOIN APPOINTMENT_INFO;
SELECT PATIENT.NAME,PATIENT.ADDERSS FROM PATIENT,APPOINTMENT_INFO WHERE APPOINTMENT_INFO.APPOINTMENT_DATE='01-SEP-23';
SELECT DOCTOR.* FROM DOCTOR,PATIENT WHERE ADDERSS = 'DHK';
SELECT PATIENT.* FROM PATIENT,DOCTOR WHERE ((DOCTOR.NAME = 'GS')OR(DOCTOR.FEE >1500));

UPDATE PATIENT
SET NAME = 'K' , ADDERSS = 'RAJ'
WHERE NAME = 'A' AND ADDERSS='DHK';

UPDATE DOCTOR
SET NAME = 'Ms. Y'
WHERE NAME = 'MR. Y';

DELETE FROM PATIENT
WHERE PATIENT_NO = 'P-101';

DELETE FROM PATIENT;
DELETE FROM DOCTOR;
DELETE FROM APPOINTMENT_INFO;
